[paper]
name        = "cdot"
sections    = [
    "abstract.md",
    "introduction.md",
    "implementation.md",
    "discussion.md",
    "figures.md",
]
supplementary = [
    "supplementary.md",
]
facts_dir    = "../output/facts"
output_dir   = "../output"
bibliography = "references.bib"
csl          = "bioinformatics.csl"
